= Backup and Recovery

The Bisq client is a hot wallet, this means there are Bitcoin and BSQ private keys stored locally on your hardware. Anyone who has access to these keys has full access and can send your money. Further, if you loose these private keys, you have lost your bitcoin, and they cannot be recovered. See chapter https://docs.bisq.network/secure-wallet.html[Secure Your Wallet] for details on the wallet password and mnemonic seed. This chapter specifically is for backing up the entire bisq client.

== Why is this Important

Please note, that you need to create a backup of the whole application directory to recover the valid application state and data. The seed words are only a backup for the on chain funds, but not for the other sensitive data included in the Bisq client. Importing seed words is only recommended for emergency cases, as the application will not be functional without a proper backup.

== What is Contained in the Backup File

* Private keys to on chain bitcoin and BSQ
* Tor hostname, onion keys, state
* Pending and closed trades, other trade statistics

== How to Create a Backup

You can create a complete backup of the entire wallet, in the *Account* menu and the *Backup* tab. *Select Backup Location* on your local computer, USB stick or CD, and click *Backup Now*. Careful though, the backup file is not encrypted, and thus anyone who has this file can take all your money! 

== How to Import a Backup
[%hardbreaks]
Shutdown the Bisq client and copy the entire backup data from your USB stick to 
Mac OSX: `~/Library/Application Support/Bisq`
Linux: `~/.local/share/Bisq`
Windows 7,8,10: `C:\Users\username\AppData\Roaming\Bisq`
Windows XP: `C:\Documents and Settings\username\Application Data\Bisq`
Make sure that you merge and replace all the existing files. Importing the backup means that you delete the current state of the wallet, so make sure you have a second backup of the status quo. Upon restart of the Bisq client, the the backup account will automatically load.
