= Bitcoin Core Nodes

Bisq contributors run a federation of Bitcoin Core nodes to (1) avoid relying on bloom filters to protect user privacy when connecting to arbitrary public nodes and (2) ensure Bisq connects to nodes with consistent Bitcoin Core implementations.


== Introduction

In the past, Bisq connected to arbitrary Bitcoin Core nodes, but the prospect of the SegWit2x hard fork in Fall 2017 made it clear this was not ideal—in the case of a hard fork, it would be impossible for Bisq to tell which fork a connected node was running. The SegWit2x hard fork never happened, but if it did, there was a chance transactions would execute on an undesirable fork, and even worse, a chance that transactions would execute on different forks.

Critically, bloom filters introduce serious privacy flaws when connecting to arbitrary bitcoin nodes, as chain analysis companies spy on SPV wallets. Connecting only to nodes run by trusted Bisq contributors avoids such monitoring.

Hence the decision to run a federation of Bitcoin nodes: more robust user privacy and a consistent Bitcoin Core implementation Bisq can rely on.

Note: Bisq users can still choose to connect to arbitrary public nodes, as before, or even connect to specific nodes they prefer.

== Infrastructure

=== GitHub

Issues are managed in the {gh-org}/bisq-btcnode[bisq-network/bisq-btcnode] repository.

=== Slack

Discussion of Bitcoin Core node status and updates takes place in the `#bisq-btcnode` Slack channel.


== Roles


=== Maintainer

The contributor(s) responsible for full node <<infrastructure>> and <<process>>.footnote:[See link:roles.html#maintainer[]]

==== Role Issue

{gh-org}/roles/issues/66[bisq-network/roles#66] footnote:[See link:roles.html#issue[]]

==== Role Team
:btcnode-maintainers: {gh-team}/btcnode-maintainers[@bisq-network/btcnode-maintainers]

{btcnode-maintainers} footnote:[See link:roles.html#team[]]

==== Duties

 * Monitor communications on the `#bisq-btcnode` Slack channel.footnote:[See link:roles.html#communication[]]
 * Keep this documentation up to date (in particular, the <<process>> detailed below).footnote:[See link:roles.html#documentation[]]
 * Write a monthly report on the Bitcoin Node Maintainer <<role-issue>>.footnote:[See link:roles.html#reporting[]]

==== Rights

 * Write access to the {gh-org}/bisq-btcnode[bisq-network/bisq-btcnode] repository.

=== Operator

The contributor(s) responsible for keeping full nodes running as outlined in <<process>>.footnote:[See link:roles.html#maintainer[]]

==== Role Issue

{gh-org}/roles/issues/67[bisq-network/roles#67] footnote:[See link:roles.html#issue[]]

==== Role Team
:btcnode-operators: {gh-team}/btcnode-operators[@bisq-network/btcnode-operators]

{btcnode-operators} footnote:[See link:roles.html#team[]]

==== Duties

 * Operate bitcoin nodes as detailed below in <<process>>.
 * Monitor communications on the `#bisq-btcnode` Slack channel.footnote:[See link:roles.html#communication[]]
 * Write a monthly report on the Bitcoin Node Operator <<role-issue>>.footnote:[See link:roles.html#reporting[]]

==== Rights

 * N/A


== Process

[ the following is a rough outline in need of feedback and with blanks to fill ]

=== Step 0. Evaluate

Determine if this is really a role you can fill. It's expected that your node will maintain (1) good uptime and (2) an up-to-date config and bitcoind version (as required by the Bitcoin Node Maintainer). There are no strict requirements for either, but it's expected that you will make your best effort to stay current.

=== Step 1. Get in Touch

Contact the Bitcoin Core Maintainer to convey your intention of setting up a Bitcoin Core node for Bisq.

=== Step 2. Set it Up

Set up a Bitcoin Core node, making sure to use the configuration https://github.com/bisq-network/bisq-btcnode[specified here] [where is it, actually?]. Also make sure your node runs in a secure environment [ details? ] and that it allows onion connections so Bisq can connect to it.

=== Step 3. Include Node in Bisq Source

Once your node is ready, send a PR to include it as a Bitcoin Core node for Bisq (they're currently specified https://github.com/bisq-network/bisq/blob/master/core/src/main/java/bisq/core/btc/nodes/BtcNodes.java[here]).
