= All About the Bisq DAO
:imagesdir: ./images
:!figure-caption:

Here we collect resources to help you learn more about the Bisq DAO, what it is, and how it works.

== General Info

==== <<user-dao-intro#, Introduction to the Bisq DAO (doc)>>
Plain language introduction to the Bisq DAO.

==== https://www.youtube.com/playlist?list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e[Bisq DAO in Brief (videos)^]
Quick, short video series on the Bisq DAO. Get up to speed with a handful of 3-4 minute videos.

==== https://www.youtube.com/playlist?list=PLFH5SztL5cYOLdYJj3nQ6-DekbjMTVhCS[Bisq DAO Basics (videos)^]
A more thorough treatment of the DAO covering everything from the basics of bitcoin transactions and colored coins to the economic and technical roots of the BSQ token and how it powers the Bisq DAO.

== User Guides

==== <<getting-started-dao-traders#, User Guide For Traders>>
This doc shows you how to use BSQ to get lower trading fees while compensating Bisq contributors at the same time.

==== <<getting-started-dao#, User Guide For Contributors>>
This doc shows you how to use the Bisq DAO to govern Bisq by walking you through the process of making a proposal and voting.

==== <<compensation#, How to Make a Compensation Request>>
Contributed to the Bisq Network? Great (and thank you!). Here is how to request compensation for your work.

== More Details

==== <<dao-user-reference#, Bisq DAO User Reference>>
Practical details on using the DAO, along with a brief technical overview: read this to understand what happens behind the scenes as you use the DAO.

==== <<dao/phase-zero#, Phase Zero: A Plan for Bootstrapping the Bisq DAO>>
An overview of the philosophy behind Bisq, the Bisq DAO, why both were created, and how it planned to decentralize its own governance from the very beginning.

==== <<dao-technical-overview#, Bisq DAO Technical Overview>>
Technical details of (1) what BSQ tokens actually are, how they're created, and how they're destroyed and (2) the various functions of the Bisq DAO and how BSQ enables them. The document includes several example transactions so you can explicitly see the processes.

== Still Curious?

We're happy to help. Feel free to reach out on https://keybase.io/team/bisq[Keybase^], https://bisq.community[the forum^], or https://twitter.com/bisq_network[Twitter^].
