= All About the Bisq DAO
:imagesdir: ./images
:!figure-caption:

Here we collect resources to help you learn more about the Bisq DAO, what it is, and how it works.

== General Info

==== <<user-dao-intro#, Introduction to the Bisq DAO (doc)>>
Plain language introduction to the Bisq DAO.

==== https://www.youtube.com/playlist?list=PLFH5SztL5cYPAXWFz-IMB4dBZ0MEZEG_e[Bisq DAO in Brief (videos)^]
Quick, short video series on the Bisq DAO. Get up to speed with a handful of 3-4 minute videos.

==== https://www.youtube.com/playlist?list=PLFH5SztL5cYOLdYJj3nQ6-DekbjMTVhCS[Bisq DAO Basics (videos)^]
A more thorough treatment of the DAO covering everything from the basics of bitcoin transactions and colored coins to the economic and technical roots of the BSQ token and how it powers the Bisq DAO.

== More Details

==== <<dao-user-reference#, Bisq DAO User Reference>>
Practical details on using the DAO, along with a brief technical overview: read this to understand what happens behind the scenes as you use the DAO.

==== <<dao/phase-zero#, Phase Zero: A Plan for Bootstrapping the Bisq DAO>>
An overview of the philosophy behind Bisq, the Bisq DAO, why both were created, and how it planned to decentralize its own governance from the very beginning.

==== <<dao-technical-overview#, Bisq DAO Technical Overview>>
Technical details of (1) what BSQ tokens actually are, how they're created, and how they're destroyed and (2) the various functions of the Bisq DAO and how BSQ enables them. The document includes several example transactions so you can explicitly see the processes.

==== https://www.youtube.com/watch?v=McaBSRj-bTk[Dev Session on the Bisq DAO^]
A thorough look at the technical implementation of the Bisq DAO. It's a fairly advanced treatment of the DAO that assumes you are already familiar with its basic ideas and workings.

== For Contributors

==== <<getting-started-dao#, For Contributors: Making a Proposal in the DAO (doc)>>
This document became outdated with the launch of the Bisq DAO on mainnet, and while it will be updated soon, keep in mind the basic processes of making proposals and voting remain largely the same.

==== <<compensation#, How to Make a Compensation Request (doc)>>
Contributed to the Bisq Network? Great (and thank you!). Here is how to request compensation for your work.

[#get-added-to-genesis]
==== <<compensation#get-added-to-genesis, BSQ Genesis Distribution>>
The BSQ genesis transaction was made on April 15, 2019. See details <<compensation#get-added-to-genesis, here>>.

== Still Curious?

We're happy to help. Feel free to reach out on https://bisq.network/slack-invite[Slack^], https://bisq.community[the forum^], or https://twitter.com/bisq_network[Twitter^].
