= Getting Started with Bisq

From : https://github.com/m52go/bisq-docs/blob/getting-started/getting-started.adoc

1st sentence = original material

2nd sentence = suggestion

the only constraint is that one side of each Bisq trade must always be bitcoin.

the only constraint is (at the moment) that one side of each Bisq trade must always be bitcoin.


To run Bisq, download and install it from the Bisq downloads page. Optional: before installing, verify the signatures of the 

Maybe insert a carriage return before Optional


Unlike most exchanges, Bisq doesn’t run a centralized server for making and taking offers, so trading on a website isn’t possible.

Unlike most exchanges, Bisq doesn’t run a centralized server for making and taking offers, so trading on a centralized website isn’t possible.


This means that if you want to use the Bisq Network, you’ve got to download and run the software too!

This means that if you want to use the Bisq Network, you’ve got to download and run the software too! Your computer becomes a member of the decentralized trading website.



