= Bisq Glossary


== Fundamentals

=== Asset
Property divisible into and transferrable as fungible <<units>>.

[example]
The US dollar and bitcoin are assets.

[[units, Units]]
=== Unit
The atomic transferable value of an <<asset>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#unit]

[example]
The penny is the US dollar unit. The satoshi is the bitcoin unit.

=== Bisq
A peer-to-peer <<asset>> exchange system. Aka _Bisq Network_.

[example]
People use Bisq to exchange bitcoin with US dollars and other assets.

=== User
A person who uses <<Bisq>>.

=== Contributor
A person who improves <<Bisq>>.

=== Owner
A person controlling certain <<units>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#owner]

=== Amount
A number of <<units>>.

=== Price
The <<amount>> of an <<asset>> expected in exchange for one <<bitcoin>>.

=== bitcoin
The <<asset>> of account on the <<Bitcoin>> network. Aka _BTC_.

[example]
I sent 0.011 bitcoin to a family member today.

=== Bitcoin
A peer-to-peer electronic cash system.footnote:[https://bitcoin.org/bitcoin.pdf] Aka _Bitcoin network_.

[example]
I've been studying the way the Bitcoin protocol works.


== Trading

=== Trade
An exchange of <<bitcoin>> for another <<asset>>.

=== Trader
A <<user>> who has agreed to <<settle>> one side of a <<trade>>.

=== Settle
To complete payment. +
_w. object:_ To complete payment for _object_.

=== Buyer
The <<trader>> who will <<settle>> by sending their <<asset>> to the <<seller>>.

[example]
Alice is the buyer. She will send 3,000 US dollars to Bob as payment for 0.5 of his bitcoin.

=== Seller
The <<trader>> who will <<settle>> by sending their <<bitcoin>> to the <<buyer>>.

[example]
Bob is the seller. He will send 0.5 of his bitcoin to Alice after receiving her payment.

=== Arbitrator
A <<contributor>> who performs <<arbitration>>.

[example]
Charlie is the arbitrator. He is standing by in case of dispute.

=== Arbitration
The service of working with <<buyer>> and <<seller>> to resolve a <<dispute>>.

[example]
Charlie has performed arbitration hundreds of times.

=== Dispute
A problem during a <<trade>>.

[example]
The dispute is about the amount Alice paid Bob.

=== Dispute Ticket
A request for <<arbitration>>.

[example]
Bob opened a dispute ticket and explained to Charlie that he had received 10 dollars too few from Alice.


[[terms, Terms]]
== Trade Terms
The conditions required to <<settle>> both sides of a <<trade>>.

=== Trade Amount
The <<amount>> of <<bitcoin>> to be traded.

[example]
The trade amount is `0.1 BTC` (1,000,000 satoshis).

=== Trade Price
The <<price>> both <<trader, Traders>> have agreed to pay.

[example]
The trade price is `1,000.00 USD/BTC`.

=== Payment Amount
The <<trade-amount>> multiplied by the <<trade-price>>.

[example]
The payment amount is `100.00 USD` (0.1 BTC * 1,000.00 USD/BTC).

=== Payment Method
The means with which the <<buyer>> will <<settle>>.

[example]
The payment method is `Cash Deposit`.


== Offers

=== Offer
A proposal to buy or sell <<bitcoin>> under certain <<terms>>.

=== Bid
An <<offer>> to buy <<bitcoin>>.

=== Ask
An <<offer>> to sell <<bitcoin>>.

=== Maker
A <<user>> who creates an <<offer>>.

[example]
Bob was the maker. It was his ask that Alice accepted.

=== Taker
A <<user>> who accepts an <<offer>>.

[example]
Alice was the taker. It was her first time using Bisq.


== Markets

=== Market
The trade between certain <<asset, Assets>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#market]

[example]
Bisq's EUR/BTC market is the most active, followed by USD/BTC.

=== Market Price
A moving average of <<price, Prices>> in a given <<market>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#price] Aka _Spot Price, Exchange Rate_.

[example]
The market price on March 27th 2017 at 12:00 CET was `1,000.00 USD/BTC` according to BitcoinAverage.

=== Volume
The <<amount>> of <<bitcoin>> traded over a given time period.

[example]
24-hour volume was 4.23 BTC.

=== Depth
The <<amount>> of <<bitcoin>> available for to buy or sell in a <<market>>.

[example]
The sell side of the USD/BTC market has a depth of 1.25 BTC.

=== Spread
The percentage difference between the best (lowest-priced) <<ask>> and the best (highest-priced) <<bid>> divided by the <<market-price>>.

[example]
The spread in the USD/BTC market is 2% right now.

[NOTE]
.Example
====
If the best <<ask>> is **1,050 USD** and the best <<bid>> is **950 USD** and the <<market-price>> is **1,000 USD**, then the BTC/USD market spread is `(1050-950)/1000` or **10%**.
====

[TIP]
.Putting spreads to use
====
Spreads indicate different kinds of opportunities in a market. A 0% spread indicates an opportunity to trade at the market price. A positive spread (as in the example above) indicates an opportunity to make a better offer and to profit when your offer is taken more quickly than others. A negative spread indicates an opportunity to take an underpriced offer and to acquire bitcoin at a discount.
====

=== Offer Book
A visual representation of open <<offer, Offers>> in a given <<market>>.


== Trade Details

=== Trade Date
The date an <<offer>> was taken.

[example]
The trade date is `March 27th 2017 at 12:00 CET`.


== Payment Accounts

=== Fiat Payment Accounts

=== Crypto Payment Accounts


== Portfolio

=== Open Offer

=== Open Trade

=== Completed Trade

=== Failed Trade


== Fees

=== Mining Fee

=== Trading Fee

=== Maker Fee

=== Taker Fee


== Fraud Protection

=== Security Deposit

The <<amount>> of bitcoin each <<trader>> must place in <<escrow>>.

[example]
The buyer's security deposit was 0.01 BTC; the seller's was 0.003 BTC.

=== Per-Trade Limits

=== Payment Account Maturity

=== Payment Method Selection


== Escrow

=== Escrow Amount
The <<trade-amount>> and the <<security-deposit>> from each <<trader>>.

=== Escrow Address
A <<multisig-address>> that requires two among the <<buyer>>, <<seller>> and <<arbitrator>> to sign.

=== Multisig Address
A <<bitcoin>> address requiring multiple signatures to authorize a transaction.

=== Escrow Deposit
The process of sending the <<escrow-amount>> to the <<escrow-address>> when a <<trade>> begins.

=== Escrow Payout
The process of sending the <<escrow-amount>> from the <<escrow-address>> to its rightful <<owner, owners>> when a <<trade>> completes.


== Bitcoin Transactions

=== Maker Fee Transaction

=== Taker Fee Transaction

=== Escrow Deposit Transaction

=== Escrow Payout Transaction



== Wallet (Aka. Funds)

=== Available Balance

=== Reserved Balance

=== Locked Balance


== Network Components

=== Component
Software that performs a specific function.

=== Critical component

=== Ancillary component

=== Trusted component

=== Bisq Desktop

=== Bisq Core

=== Bisq P2P

=== Bisq Seednode

=== Bisq Pricenode

=== Bisq Bitcoin Node

=== Bisq Website

=== Bisq Markets Website

=== Bisq Markets API


== Network Infrastructure

=== Infrastructure

=== Repository


== Contributing

=== Stakeholder
An <<owner>> of <<BSQ>>.

=== Bonded Contributor
A <<contributor>> who TODO

=== Bonding

=== Compensation

=== Voting


== Roles

=== Operator
A <<bonded-contributor>> who operates a <<trusted-component>>.

=== Maintainer
A <<bonded-contributor>> who maintains a <<repository>>.

=== Moderator

=== Admin


== Uncategorized

=== Attacker
A person who attempts to damage <<Bisq>>.

=== Scammer
A dishonest <<trader>> who attempts to defraud others of their <<asset>>. Aka _Fraudster_.

=== Fiat
A <<currency>> issued by a national authority. Aka _Fiat Currency, National Currency_.

=== Crypto

=== Account

=== Security Deposit

=== Multisig Escrow

=== Deposit Transaction

=== Mining Fee

=== Trading Fee

=== Fixed Trade Price
A <<trade-price>> whose value is assigned at <<offer>> creation time.

[example]
This trade's price is fixed at 1,000 USD/BTC.

=== Floating Trade Price
A <<trade-price>> whose value is assigned at <<offer>> acceptance time by multiplying the <<market-price>> by a `percent distance from market price` premium.

[example]
This trade's price is set to float at 2% above market price.

=== BSQ
The <<bitcoin>>-based colored coin used in Bisq funding and governance transactions. Aka _BSQ token_.

[example]
BSQ has five utilities: earning, trading, spending, voting and bonding.

=== BSQ (system)
The <<component, Components>> and consensus protocol that validate <<BSQ>> transactions.

=== Proposal

=== Compensation Request

=== Meritocracy

=== Radical Transparency

=== Work on What You Want


== Appendix: Notes and recommendations

 . Introduce 'Bid' and 'Ask' terms in the UI, API
 . Normalize presentation of market pairs, such that BTC is always the denominator, e.g. USD/BTC = 6,500 USD / 1 BTC; XMR/BTC = n XMR / 1 BTC.
   - UPDATE: kill the BTC entirely in most contexts. It's half of every trade. So just talk about Bisq's USD market, XMR market, etc. When displaying market prices, do it like this: `Market Price: 6552.50 USD/BTC`. Note how BTC is in the denominator here, as it should be. (currently we put it in the numerator of the market)
 . i.e. do not flip things around for altcoin / crypto trades. They're just another payment method as far as Bisq is concened. In Bisq, BTC is money. It's half of every trade. It's the unit of account. All prices here are denominated in it.
 . Change `Market` to `Markets` in top nav
 . Rename `Account` to `Payment Accounts`
   - Rename `National Currency Accouts` to `Fiat Payment Accounts`
   - Rename `National Currency Accouts` to `Crypto Payment Accounts`
   - Extract `Arbitrator Selection`, `Wallet Password` and other tabs to `Settings`
 . Rename `Funds` => `Wallet`
   - Rename `Receive funds` to `Receive BTC`
   - Rename `Send funds` to `Send BTC`
   - Rename `Send funds` to `Send BTC`
   - Rename `Reserved funds` to `Reserved Balance`
   - Rename `Locked funds` to `Locked Balance`
 . Rework `Asset` hierarchy to include fiat
   - Use emoji flags for national currencies?
   - Repackage to `bisq.{=>core}.asset`? (would reflect that physical separation of repo is for practical purposes, would allow nat'l / fiat currency implementations to live in bisq-core.
