= Bisq Glossary


== Fundamentals

=== User
A person who uses <<Bisq>>.

=== Contributor
A person who improves <<Bisq>>.

=== Bisq
////
A peer-to-peer Bitcoin foreign exchange network. Aka _Bisq Network_.

A peer-to-peer Bitcoin trading network. Aka _Bisq Network_.

A peer-to-peer Bitcoin exchange network. Aka _Bisq Network_.

A peer-to-peer bitcoin exchange network. Aka _Bisq Network_.

A peer-to-peer Bitcoin asset exchange network. Aka _Bisq Network_.

A peer-to-peer exchange network for Bitcoin. Aka _Bisq Network_.

A peer-to-peer Bitcoin <<asset>> exchange network. Aka _Bisq Network_.

A peer-to-peer <<asset>> exchange network for Bitcoin. Aka _Bisq Network_.
////
A peer-to-peer <<asset>> exchange network. Aka _Bisq Network_.

=== Asset
Property divisible into and transferrable as fungible <<units>>.

> The US dollar and bitcoin are assets.

[[units, Units]]
=== Unit
The atomic transferable value of an <<asset>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#unit]

> The penny is the US dollar unit. The satoshi is the bitcoin unit.

=== Owner
A person controlling certain <<units>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#owner]

=== Amount
A number of <<units>>.

=== Price
The <<amount>> of an <<asset>> expected in exchange for one <<bitcoin>>.

Aka _Exchange Rate_.

=== bitcoin
The <<asset>> of account on the <<Bitcoin>> network. Aka _BTC_.

> You have to spend bitcoin to transact on the Bitcoin network.

=== Bitcoin
The concept of Bitcoin; the entire network itself.footnote:[Adapted from https://bitcoin.org/en/vocabulary#bitcoin]

> I was learning about the Bitcoin protocol today.

=== BSQ
The <<bitcoin>>-based colored coin that underpins Bisq funding and governance. Aka _BSQ token_.

> BSQ has five utilities: earning, trading, spending, voting and bonding.

=== BSQ (system)
The <<components>> and consensus protocol that validate <<BSQ>> transactions.

== Trading

=== Trade
To exchange <<bitcoin>> for another <<asset>>. +
_n._ The exchange of <<bitcoin>> for another <<asset>>.

=== Trader
A <<user>> who has agreed to <<settle>> in one side of a <<trade>>.

=== Settle
To complete payment of an <<amount>>.

=== Buyer
The <<trader>> who <<settle, settles>> by sending their <<asset>> to the <<seller>>.

=== Seller
The <<trader>> who <<settle, settles>> by releasing their <<bitcoin>> to the <<buyer>>.

=== Arbitrator
A <<contributor>> who performs <<arbitration>>.

=== Arbitration
The service of working with <<buyer>> and <<seller>> to resolve a <<dispute>>.

=== Dispute
A problem with a <<trade>>.

> The dispute was over the amount the buyer paid the seller.

=== Dispute Ticket
A request for <<arbitration>>.

> The seller opened a dispute ticket after receiving too little in payment from the buyer.


== Markets

=== Market Price
A moving average of a given <<price>>.
//Aka _Spot Price_.

> The market price on Nov 16th at 16:12 CET was `1,000.00 USD/BTC` according to BitcoinAverage.


== Trade Terms

=== Terms
The conditions to <<settle, settling>> a trade, including <<trade-amount>>, <<trade-price>>, <<payment-amount>> and <<payment-method>>.

=== Trade Amount
The <<amount>> of bitcoin to be traded.

> The trade amount was `0.1 BTC` (1,000,000 satoshis)

=== Trade Price
The <<price>> both <<trader, Traders>> have agreed to pay.

> The trade price was `1,010.00 USD/BTC`

==== Fixed Trade Price

A <<trade-price>> whose value is assigned at <<offer>> creation time.

> This trade's price is fixed at 1,000 USD/BTC

==== Floating Trade Price

A <<trade-price>> whose value is assigned at <<offer>> acceptance time by multiplying the <<market-price>> by a `percent distance from market price` premium.

> This trade's price is set to float at 2% above market price

=== Payment Amount
The <<trade-amount>> multiplied by the <<trade-price>>.

> The payment amount was `101.00 USD` (0.1 BTC * 1,010.00 USD/BTC)

=== Payment Method
The means with which the <<buyer>> will <<settle>>.

> The payment method was `Cash Deposit`.

See <<payment-methods#, Payment Methods>>.


== Trade Details

=== Trade Date
The date an <<offer>> is taken.

> The trade date was `Nov 16th at 16:12 CET`


== Offers

=== Maker
A <<user>> who creates an <<offer>>.

=== Taker
A <<user>> who accepts an <<offer>>.

=== Offer
An expression of intent to <<trade>> with certain <<terms>>.

=== Bid
An <<offer>> to buy bitcoin.

=== Ask
An <<offer>> to sell bitcoin.



== Contributing

=== Stakeholder
An <<owner>> of <<BSQ>>.

=== Bonded Contributor
A <<contributor>> who TODO

=== Operator
A <<bonded-contributor>> who operates a <<trusted-component>>.

=== Maintainer
A <<bonded-contributor>> who maintains a <<repository>>.

=== Compensation

=== Voting

=== Offer Book
A map of all open <<offer, Offers>>, keyed by <<market>>.


== Network Components

=== Component
Software that performs a specific function. See <<Components>>.

=== Critical component

=== Ancillary component

=== Trusted component

=== Bisq Desktop

=== Bisq Core

=== Bisq P2P

=== Bisq Seednode

=== Bisq Pricenode

=== Bisq Bitcoin Node

=== Bisq Website

=== Bisq Markets Website

=== Bisq Markets API


== Network Infrastructure

=== Infrastructure

=== Repository


== Uncategorized

=== Attacker
A person who attempts to damage <<Bisq>>.

=== Scammer
A dishonest <<trader>> who attempts to defraud others of their <<asset>>.

Aka _Fraudster_.

=== Fiat
A <<currency>> issued by a national authority.

Aka _Fiat Currency, National Currency_.

=== Crypto
A

=== Depth
The amount of bitcoin available for <<trade>> in a given <<market>>.

=== Spread
// tag::spread[]
The difference between the best (lowest-priced) <<./glossary#offer, offer>> to sell and the best (highest-priced) <<./glossary#offer, offer>> to buy, divided by the market price and expressed as a percentage.
// end::spread[]
[NOTE]
.Example
====
If the best <<glossary#offer, offer>> to sell BTC is **1,050 USD** and the best offer to buy BTC is for **950 USD** and the current market price is **1,000 USD**, then the BTC/USD market spread is `((1050-950)/1000)*100)` or **10%**.
====
[TIP]
.Putting spreads to use
====
Spreads indicate different kinds of opportunities in a market. A 0% spread indicates an opportunity to trade at the market price. A positive spread (as in the example above) indicates an opportunity to make a better offer and get it taken more quickly. A negative spread indicates an opportunity to take an underpriced offer and profit from it. See <<./glossary.adoc#arbitrage, arbitrage>>.
====

=== Market
The trade between a certain pair of assets. As in "the BTC/USD and BTC/XMR markets".

=== Volume
The amount of a given number of units traded in a given time period.

=== Account

=== Security Deposit
def

=== Multisig Escrow
def

=== Deposit Transaction
def

=== Mining Fee
def

=== Trading Fee
def


== Appendix: Notes and recommendations

 . Introduce 'Bid' and 'Ask' terms in the UI, API
 . Normalize presentation of market pairs, such that BTC is always the denominator, e.g. USD/BTC = 6,500 USD / 1 BTC; XMR/BTC = n XMR / 1 BTC.
 . i.e. do not flip things around for altcoin / crypto trades. They're just another payment method as far as Bisq is concened. In Bisq, BTC is money. It's half of every trade. It's the unit of account. All prices here are denominated in it.
