= Bisq Glossary


== Fundamentals

=== User
A person who uses <<Bisq>>.

=== Contributor
A person who improves <<Bisq>>.

=== Bisq
////
A peer-to-peer Bitcoin foreign exchange network. Aka _Bisq Network_.

A peer-to-peer Bitcoin trading network. Aka _Bisq Network_.

A peer-to-peer Bitcoin exchange network. Aka _Bisq Network_.

A peer-to-peer bitcoin exchange network. Aka _Bisq Network_.

A peer-to-peer Bitcoin asset exchange network. Aka _Bisq Network_.

A peer-to-peer exchange network for Bitcoin. Aka _Bisq Network_.

A peer-to-peer Bitcoin <<asset>> exchange network. Aka _Bisq Network_.

A peer-to-peer <<asset>> exchange network for Bitcoin. Aka _Bisq Network_.
////
A peer-to-peer <<asset>> exchange network. Aka _Bisq Network_.

=== Asset
Property divisible into and transferrable as fungible <<units>>.

> The US dollar and bitcoin are assets.

[[units, Units]]
=== Unit
The atomic transferable value of an <<asset>>.footnote:[Adapted from https://github.com/libbitcoin/libbitcoin/wiki/Glossary#unit]

> The penny is the US dollar unit. The satoshi is the bitcoin unit.

=== Maker
A <<user>> who creates an <<offer>>.

=== Taker
A <<user>> who accepts an <<offer>>.

=== Offer
An expression of intent to <<trade>> with certain <<terms>>.

=== Bid
An <<offer>> to buy bitcoin.

=== Ask
An <<offer>> to sell bitcoin.

=== Trade
To exchange bitcoin for another <<asset>>. +
_n._ The exchange of bitcoin for another <<asset>>.

=== Trader
A <<user>> bound by contract to <<settle>>.

=== Settle
To complete payment of an <<amount>> owed.

=== Amount
A number of <<units>>.

=== Buyer
A <<trader>> who buys another's bitcoin in exchange for their own <<asset>>.

=== Seller
A <<trader>> who sells their own bitcoin in exchange for another's <<asset>>.

=== Arbitrator
A <<contributor>> who performs <<arbitration>>.

=== Arbitration
The service of working with <<buyer>> and <<seller>> to resolve a <<dispute>>.

=== Dispute
A problem with a <<trade>>.

> The seller opened a dispute after receiving less in payment than expected.


== Trading

=== Terms
The requirements to <<settle>>, including <<trade-amount>>, <<trade-price>>, <<payment-amount>> and <<payment-method>>.

// > The terms specified that the buyer would purchase 0.625 BTC from the seller at a price of 6425.89 USD via the Zelle payment network.

=== Trade Amount
The <<amount>> of bitcoin to be traded.

> The trade amount was `0.1 BTC` (1,000,000 satoshis)

=== Trade Date
The date an <<offer>> is taken.

> The trade date was `Nov 16th at 16:12 CET`

=== Price
The <<amount>> of an <<asset>> expected in exchange for one bitcoin.

Aka _Exchange Rate_.

=== Market Price
A moving average of a given <<price>>.
//Aka _Spot Price_.

> The market price on Nov 16th at 16:12 CET was `1,000.00 USD/BTC` according to BitcoinAverage.

=== Trade Price
The <<price>> agreed on for a given <<trade>>, which may differ from the <<market-price>>.

> The trade price was `1,010.00 USD/BTC` – 1% above the market price.

=== Payment Amount
The <<trade-amount>> multiplied by the <<trade-price>>.

> The payment amount was `101.00 USD` (0.1 BTC * 1,010.00 USD/BTC)

=== Payment Method
The means with which the <<buyer>> will <<settle>>.

> The payment method was `Cash Deposit`.

See <<payment-methods#, Payment Methods>>.


== Contributing

=== Stakeholder
A <<contributor>> who <<own, Owns>> <<BSQ>> and is eligible to <<vote>>.

=== Bonded Contributor
A <<contributor>> who TODO

=== Operator
A <<bonded-contributor>> who operates a <<trusted-component>>.

=== Maintainer
A <<bonded-contributor>> who maintains a <<repository>>.

=== Attacker
A person who attempts to damage <<Bisq>>.

=== Scammer
A dishonest <<trader>> who attempts to defraud others of their property.

Aka _Fraudster_.


=== BSQ
Bisq's Bitcoin-based utility token that owners can trade for bitcoin, spend on trading fees, vote, bond, and earn.
[NOTE]
.BSQ the token vs BSQ the system
====
TODO
====

=== Compensation

=== Voting

=== Own
A person controlling certain <<units>>.

=== Offer Book
A map of all open <<offer, Offers>>, keyed by <<market>>.


== System

=== Bisq
The system of <<components>> that work together to make . Also referred to as the _Bisq Network_.

=== Component
Software that performs a specific function. See <<Components>>.

=== Critical component

=== Ancillary component

=== Trusted component

=== Bisq Desktop

=== Bisq Core

=== Bisq P2P

=== Bisq Seednode

=== Bisq Pricenode

=== Bisq Bitcoin Node

=== Bisq Website

=== Bisq Markets Website

=== Bisq Markets API



=== Repository



=== Currency
def

=== Bitcoin
def

=== Fiat
A <<currency>> issued by a national authority.

Aka _Fiat Currency, National Currency_.

=== Crypto
A

=== Depth
The amount of bitcoin available for <<trade>> in a given <<market>>.

=== Spread
// tag::spread[]
The difference between the best (lowest-priced) <<./glossary#offer, offer>> to sell and the best (highest-priced) <<./glossary#offer, offer>> to buy, divided by the market price and expressed as a percentage.
// end::spread[]
[NOTE]
.Example
====
If the best <<glossary#offer, offer>> to sell BTC is **1,050 USD** and the best offer to buy BTC is for **950 USD** and the current market price is **1,000 USD**, then the BTC/USD market spread is `((1050-950)/1000)*100)` or **10%**.
====
[TIP]
.Putting spreads to use
====
Spreads indicate different kinds of opportunities in a market. A 0% spread indicates an opportunity to trade at the market price. A positive spread (as in the example above) indicates an opportunity to make a better offer and get it taken more quickly. A negative spread indicates an opportunity to take an underpriced offer and profit from it. See <<./glossary.adoc#arbitrage, arbitrage>>.
====

=== Market
The trade between a certain pair of assets. As in "the BTC/USD and BTC/XMR markets".

=== Volume
The amount of a given number of units traded in a given time period.

=== Account

=== Security Deposit
def

=== Multisig Escrow
def

=== Deposit Transaction
def

=== Mining Fee
def

=== Trading Fee
def
