= Roles

Roles are the means by which responsibility over specific Bisq Network components, infrastructure and processes is delegated to individual contributors.


== Introduction

The Bisq DAO is a flat organization, without traditional management or reporting structures. At the same time, there are many vital resources and processes that must be cared for by individuals. For example, someone must manage the DNS for the https://bisq.network[bisq.network] domain, someone must admininister the {gh-org}[bisq-network] GitHub organization, and so on.

And because the Bisq DAO is not a volunteer organization, but one that compensates valuable contributions, it must be possible for stakeholders to assess how these resources and processes are being cared for over time so as to know whether and how much to compensate those in charge of them.

What's needed is a mechanism that defines each of these responsibilities, makes it clear who is responsible for them, and that includes a process for regular reporting and feedback. The system of roles described below provide that mechanism.


== Infrastructure

=== GitHub

==== Issues

Roles are managed as issues in the {gh-org}/roles/issues[bisq-network/roles] repository.

 - Assignees used to track role ownership
 - Description field used to
   - Link to team
   - Indicate who is primary
   - Link to role documentation
 - Comments used for
   - monthly reporting
   - customer feedback
 - Anyone can subscribe to any issue or watch the whole repo to stay up to date with reporting
 - Labels used to
   - Indicate `help wanted`

==== Teams

Managed as GitHub Teams. For @mentions and to institutionalize thinking in terms of roles not individuals.

=== Docs

There is no "role documentation" per se, but rather there is documentation about whatever component or infrastructure a given role is responsible for, and in that documentation, there is a section for the role.

=== Slack

Slack.


== Anatomy of a role

=== Duties

A role's _duties_ are the activities that the role's owner must carry out in order to be compensated for their efforts. For example, repository maintainers must enforce review process and merge pull requests in a timely fashion, the website operator must keep the site up and running at all times, and so forth.

=== Rights

Most roles involve some special _rights,_ such as exclusive permissions or access to a given resource. For example, a maintainer of a bisq-network GitHub repository will have write permissions to that repository such that they can merge contributors' pull requests, the operator of the bisq.network website will have administrative access to the infrastructure that hosts the site, and so forth.

=== Owners

Each role has one or more _owners,_ with one being designated as _primary_ and others being designated as _secondary_.footnote:[See {gh-org}/proposals/issues/12] The primary role owner is responsible for carrying out the day to day activities of that role, while secondary owners are standing by, fully capable of taking over for the primary owner in case of sickness or other incapacitation.


== Common role duties

=== Reporting

=== Communication

Respond to issues in any repositories

Respond to inquiries in Slack

Generally means setting up notifications appropriately.

=== Documentation

Specifically, keeping your own role's documentation up to date


== Common role types

=== Maintainer

=== Operator

=== Administrator

=== Moderator


== Compensation


== Bonding


== Proceseses

=== Proposing a new role

=== Transferring ownership

=== Changing primary / secondary status

=== Adding a secondary

=== Providing feedback to role owners


[roles-maintainer]
== The Roles Maintainer role

The system of roles described above is a collection of infrastructure and processes like any other in the Bisq DAO, and requires a maintainer to care for it.

https://github.com/bisq-network/roles/issues/28

=== Duties

All normal <<maintainter>>

=== Rights


== Notes

replace the proto-documentation we did for roles in the Phase Zero doc, particularly that found at docs.bisq.network/dao/phase-zero.html#bonded-contributor-roles

capture the decisions we've made around roles in bisq-network/proposals#12 and bisq-network/proposals#13 and bisq-network/proposals#14

document the way the bisq-network/roles repository works and document the responsibilities of the roles maintainer (bisq-network/roles#28).

cover the relationship between role issues, GitHub teams, primary/secondary role owners

document, or at least carve out a placeholder for documenting, the way bonding and BSQ interest payments will work for bonded contributor roles.

document the process for creating a new role, which will likely involve submitting a proposal for a new role, similar to the way this one was done

Update https://docs.bisq.network/dao/phase-zero.html#Appendix-A

Close https://github.com/bisq-network/bisq-docs/issues/46

Maintainer role must be fully separated from reviewer role. Maintainers validate that pull requests are correct, maintainers ensure that overall process is followed, maintainers give enough time for sufficient review, and then, maintainers merge pull requests. When somone is _reviewing_ a pull request, even if that person is a maintainer, they are not wearing their maintainer hat. They are wearing their _contributor_ hat. Maintainers do not review. See https://github.com/bisq-network/roles/issues/63#issuecomment-393453744 for counter-example of this. Reviewing puts too much on maintainers.

////
.Example
----
DNS Admin

Assignees: @cbeams, @ripcurlx
Description:
    Team: @bisq-network/dns-admins
    Primary: @cbeams
    Docs: https://docs.bisq.network/dns.html#admin
----
////

TIP: Subscribe to individual role issues or watch the entire repository to stay up to date with role reports.
