= Bisq DAO Roles

Roles are the way contributors take responsibility for Bisq Network resources and processes.


== Introduction

The Bisq DAO is a flat organization, without traditional management or reporting structures. At the same time, there are many vital resources and processes that must be cared for by individuals. For example, someone must manage the DNS for the `bisq.network` domain, someone must conduct monthly stakeholder voting, and so on.

What's needed is a mechanism that defines these various duties, makes it clear who is responsible for each, and that includes a process for regular reporting and feedback. The system of _roles_ described below provides such a mechanism.


[[characteristics]]
== Characteristics of a role

=== Duties

Actions that must be performed for a certain resource or process to function normally.

For example, a repository maintainer's duties include merging pull requests in a timely fashion, and the website operator's duties include keeping the site available at all times.

=== Rights

Special permissions or other access required to perform the <<duties>> of a role.

For example, a repository maintainer's rights include write permissions to their repository, and the website operator's rights include administrative access to site hosting infrastructure.

=== Owners

Contributors who have the <<rights>> required to perform the <<duties>> of a role.

One owner is designated as _primary_ and any other owners are designated as _secondary_.footnote:[See {gh-org}/proposals/issues/12] The primary is responsible for performing the <<duties>> of the role, while secondaries stand by, capable of taking over for the primary at any time.


== Infrastructure

=== Docs

There is no "role documentation" per se, but rather there is documentation about whatever component or infrastructure a given role is responsible for, and in that documentation, there is a section for the role.

=== GitHub

==== Issues

Roles are managed as issues in the {gh-org}/roles/issues[bisq-network/roles] repository.

////
 - Assignees used to track role ownership
 - Description field used to
   - Link to team
   - Indicate who is primary
   - Link to role documentation
 - Comments used for
   - monthly reporting
   - customer feedback
 - Anyone can subscribe to any issue or watch the whole repo to stay up to date with reporting
 - Labels used to
   - Indicate `help wanted`
////

==== Teams

Managed as GitHub Teams. For @mentions and to institutionalize thinking in terms of roles not individuals.

=== Slack

Slack.


== Types

=== Maintainer

=== Operator

=== Administrator

=== Moderator


== Common role duties

=== Reporting

Primary role <<owners>> should submit a _monthly report_ as a comment on their <<issues, Role Issue>>.footnote:[See {gh-org}/proposals/issues/13] The report should contain whatever information the owner believes would be valuable to other users, contributors and stakeholders. The comment should be formatted in Markdown as follows:

[source,markdown]
----
## YYYY.MM report

<content>

/cc bisq-network/compensation#<number>
----

Where `<content>` is the content of the report itself, and `<number>` is the number of that contributor's monthly compensation request. https://github.com/bisq-network/roles/issues/16#issuecomment-393852612[Example].

Some roles may have nothing to report in a given month. In this case, a report should still be written stating that there is "nothing to report". https://github.com/bisq-network/roles/issues/18#issuecomment-393217596[Example].

=== Communication

Respond to issues in any repositories

Respond to inquiries in Slack

Generally means setting up notifications appropriately.

=== Documentation

Specifically, keeping your own role's documentation up to date


== Compensation


== Bonding


[roles-maintainer]
== The Roles Maintainer role

The contributor(s) responsible for roles <<infrastructure>> and <<processes>>.footnote:[See link:roles.html#maintainer[]]

[roles-maintainer-role-issue]
=== Role Issue

{gh-org}/issues/28[#28]

[roles-maintainer-duties]
==== Duties

 * Enforce the proposals <<processes>> detailed below.
 * Monitor communications on the `#roles` Slack channel.footnote:[See link:roles.html#communication[]]
 * Keep this roles documentation up to date.footnote:[See link:roles.html#documentation[]]
 * Write a monthly report on the roles maintainer <<roles-maintainer-role-issue>>.footnote:[See link:roles.html#reporting[]]

[roles-maintainer-rights]
==== Rights

 * Write access to the {gh-org}/roles[bisq-network/roles] repository

[roles-maintainer-owners]
==== Owners

See the <<roles-maintainer-role-issue>>


== Processes

=== Proposing a new role

=== Transferring ownership

=== Changing primary / secondary status

=== Adding a secondary

=== Providing feedback to role owners
