= Roles

Roles are the way contributors take responsibility for Bisq Network resources and processes.


== Introduction

The Bisq DAO is a flat organization, without traditional management or reporting structures. At the same time, there are many resources and processes vital to the operation of the network that must be cared for by individuals. For example, someone must manage the DNS for the `bisq.network` domain, someone must conduct monthly stakeholder voting, and so on. What's needed is a mechanism that defines these various duties, makes it clear who is responsible for each, and that provides a process for regular reporting and feedback. The system of _roles_ described below is designed to meet this need, with a major design goal being maximizing decentralization and keeping the organization flat as it grows.


== Properties

The following are properties common to all roles.

=== Duties

_Duties_ are actions that must be performed for a certain resource or process to function normally.

For example, a repository maintainer's duties include merging pull requests in a timely fashion, and a website operator's duties include keeping the site available at all times.

=== Rights

_Rights_ are special permissions or other access required to perform the <<duties>> of a role.

For example, a repository maintainer's rights include write permissions to their repository, and a website operator's rights include administrative access to site hosting infrastructure.

=== Owners

_Owners_ are contributors who have the <<rights>> required to perform the <<duties>> of a role.

One owner is designated as _primary_ and any other owners are designated as _secondary_.footnote:[See {gh-org}/proposals/issues/12] The primary is responsible for performing the <<duties>> of the role, while secondaries stand by, capable of taking over for the primary at any time.


== Infrastructure

The following infrastructure is used to define and manage each role.

=== Docs

Each role should be documented at https://docs.bisq.network[docs.bisq.network], not in a document of its own, but in a _section_ of a document dedicated to the larger resource or process in question.

For example, there is no "Proposals Maintainer" document, but rather a <<proposals#, Proposals>> document having a <<proposals#maintainer, Maintainer>> section within.

Each role's documentation should enumerate its <<duties>> and <<rights>> and link to its <<team>> and <<issue>>.

=== Team

Each role has a dedicated GitHub team where each of the role's <<owners>> are members. The team is used to manage access to GitHub repositories that role is responsible for and to send notifications to owners with @mentions in GitHub issues and pull requests.

For example, the {gh-team}/desktop-maintainers/members[@bisq-network/desktop-maintainers] team has write access to the {gh-org}/bisq-desktop[bisq-network/bisq-desktop] repository.

The primary role owner is also assigned as the _maintainer_ of the GitHub team, such that they may manage the team without requiring the intervention of a GitHub admin.

=== Issue

Each role has a dedicated GitHub issue in the {gh-org}/roles/issues[bisq-network/roles] repository.

 - The **Assignees** field is used to track role ownership.
 - The **Description** field is used to link to the role's <<docs>>, <<team>> and primary <<owners, Owner>>.
 - **Comments** are used for <<report, reporting>> and feedback.

See the {gh-org}/roles/issues/30[Proposals Maintainer] role issue for an example.


== Types

Most roles fit into one of the types below.

=== Maintainer

=== Operator

=== Administrator

=== Moderator


== Common duties

The following duties are common to all roles.

=== Report

Primary role <<owners>> should report once a month in the form of a comment on their <<issue>>.footnote:[See {gh-org}/proposals/issues/13] The report should contain whatever information the owner believes would be valuable to other users, contributors and stakeholders. The comment should be formatted in Markdown as follows:

[source,markdown]
----
## YYYY.MM report

<content>

/cc bisq-network/compensation#<number>
----

Where `<content>` is the content of the report itself, and `<number>` is the number of that contributor's monthly compensation request. https://github.com/bisq-network/roles/issues/16#issuecomment-393852612[Example].

Some roles may have nothing to report in a given month. In this case, a report should still be written stating that there is "nothing to report". https://github.com/bisq-network/roles/issues/18#issuecomment-393217596[Example].

=== Document

Primary role <<owners>> should document changes to their role by submitting pull requests to their role's <<docs>>.

=== Communicate

Primary role <<owners>> should respond in a timely fashion to feedback comments on their role <<issue>>, issues created in their repositories, @mentions of their <<team>>, and questions in their Slack channel.


== Compensation

TODO


== Bonding

TODO


[[roles-maintainer-role]]
== The Roles Maintainer role

Roles Maintainers are the contributors responsible for the system of roles described throughout the rest of this document.

[[roles-maintainer-issue]]
=== Issue

{gh-org}/roles/issues/28[bisq-network/roles#28]

[[roles-maintainer-team]]
=== Team

{gh-team}/roles-maintainers[@bisq-network/roles-maintainers]

[[roles-maintainer-duties]]
=== Duties

 * Follow and enforce the roles <<processes>> detailed below.
 * <<report>> monthly on the Roles Maintainer <<roles-maintainer-issue>>.
 * <<document>> changes to roles <<processes>>.
 * <<communicate>> in the `#roles` Slack channel.

[[roles-maintainer-rights]]
=== Rights

 * Write access to the {gh-org}/roles[bisq-network/roles] repository


== Processes

=== Proposing a new role

=== Transferring ownership

=== Changing primary / secondary status

=== Adding a secondary

=== Providing feedback to role owners
