= Trading and Arbitration Rules
:imagesdir: images
:!figure-caption:

_This document is under development. Subscribe to https://github.com/bisq-network/bisq-docs/issues/80[bisq-network/bisq-docs#80] for updates._

To trade on Bisq, you assume one of two roles. You either buy bitcoin (BTC buyer) or sell bitcoin (BTC seller).

This document covers the rules and expectations for each role, as well as details on the process for arbitrating disputes.

IMPORTANT: Under **no circumstances** should you try to contact a trader using the contact information in their payment details, even if you have an issue with a trade. Always go through an arbitrator. Many people use Bisq for its high degree of privacy, and discussing Bisq away from Bisq is highly likely to compromise that privacy.

NOTE: The rules listed below are default rules for every transaction. Offer makers sometimes specify their own _additional_ terms for handling/arranging payments. For example, a seller using cash deposit might require a picture of a receipt torn in half with "NO REFUND" written on it. Face-to-face traders often specify terms about where and how to meet. Make sure you're okay with an offer-maker's terms **before** you accept an offer!

== BTC buyer

* Payment should be completed reasonably early within the trade period, such that the seller has time to acknowledge receipt of the payment before the trade period is over. Waiting until the end of the trade period to make a payment is not acceptable, as then the seller cannot reasonably act in time. The lengths of trade periods vary based on payment method. See details https://bisq.network/faq/#trade-periods[here].
* Must make payment from the account used to make/take the offer. The account information (e.g., name, account number, etc) must match.
* Must enter the trade ID in the payment transfer "reason for payment" (if possible).
* Must click the "Payment started" button after making the payment.
* Any fees incurred to make the payment via the agreed payment method (e.g., bank fees for bank transfer, money-order fees for money orders, etc) are the buyer's responsibility to pay.
* In case of a dispute, buyer must collaborate with the arbitrator, responding to inquiries within 48 hours and providing materials as requested to determine an outcome.

== BTC seller

* Must click "Confirm payment" after having received payment. Has until the end of the maximum trade period to do so.
* In case of a dispute, seller must collaborate with the arbitrator, responding to inquiries within 48 hours and providing materials as requested to determine an outcome.

== Arbitration

When trading partners cannot successfully complete a trade on their own, the trade is disputed, and an arbitrator steps in to determine a solution.

The following are possible circumstances and resulting outcomes.

**The BTC buyer didn't confirm sending the funds and let the trade duration limit run out**

The arbitrator can release all the escrow funds to the BTC seller.

**The BTC seller didn't release the trade funds by confirming receipt of the funds and let the trade duration limit run out**

The BTC buyer is responsible to provide the arbitrator with proof of their payment. If they fail to do so and the BTC seller says they haven't received any funds, the BTC seller gets all the funds in escrow.
The BTC seller has 48 hours after the end of the maximum trade period to respond as to whether they have or not received the funds. After that the arbitrator can sign a transaction releasing all funds in escrow to the BTC buyer.

If you don't hear back from your arbitrator within a reasonable amount of time, your message may not have been delivered successfully by the peer-to-peer network. If this happens, you can ping your arbitrator on link:https://bisq.community/t/arbitrators/8074[the forum]. Simply find your arbitrator's forum handle by searching the forum for your arbitrator's onion address (you'll find this address in the trade information popup), and tag your arbitrator in a new forum post about your issue.

CAUTION: Be sure to create an anonymous forum account so your trade data remains private.

When facing any issue that stops you, as the BTC seller or buyer, from fulfilling your role during the trade period, a dispute should be opened immediately by pressing Cmd/Ctrl+o on the `Portfolio` > `Open trades` screen.

**The BTC buyer sent the funds to the wrong person**

The BTC seller gets all the escrow funds.

**The BTC buyer identifiers don't match the identifiers on your payment receipt**

The BTC seller gets all the escrow funds.

**The BTC seller received the funds but the BTC buyer didn't enter the correct reference text**

The BTC buyer gets the trade amount but loses their security deposit.

== Face-to-Face (F2F) Trading
[[f2f-trading]]

On Bisq, F2F trades are very similar to online trades. In fact, to carry out a F2F trade, you follow the same process within the Bisq software as you would for any other trade. The difference is in how the buyer pays the seller: instead of paying through a financial intermediary (like a bank or other money transfer service), the buyer meets the seller in real life and pays with cash.

This introduces some important differences.

=== Meeting your trading partner

Doing a transaction face-to-face means you'll be coming within close proximity of a stranger to exchange relatively substantial value.

==== Be safe

People do local, in-person commerce all the time, all over the world. Incidents are rare, but they do happen. You should be cognizant of risks and do your part to minimize potential harm.

**Guard your data.** When you set up a face-to-face payment account in Bisq, you'll need to provide contact information so you can arrange a meeting with your trading partner. Make sure this information isn't traceable back to your property or identity.

**Meet in a neutral public place.** Meeting your trading partner in a place with witnesses and security cameras significantly reduces the chance of an incident.

**Don't bring more than you need.** Even in a public place, incidents can still happen, but you can limit the chance even further by limiting valuables on your person that would interest a thief in the first place.

**Bring backup.** Consider bringing a friend with you. Also, depending on the laws in your area & your own comfort, consider carrying a concealed tool for self-defense. Even pepper-spray can hobble a criminal just enough to get you out of immediate danger.

==== Validate payment

Face-to-face trades are usually settled with cash. Cash is wonderfully anonymous, but it can be counterfeited. Be sure you know the basics of detecting counterfeit currency. For example, there are several characteristics of US dollar bills one can examine to quickly determine fakes with high accuracy.

You could look for tools like counterfeit pens to do the work for you, but make sure you do thorough research before picking one. Counterfeit pens, for example, are often not reliable.

If you'd rather not take the chance of carrying or accepting cash, consider meeting at a bank where you can validate a buyer's payment on the spot.

==== Ensure you follow Bisq protocol

Ultimately, the deal will be completed in Bisq. Buyers must mark payment as sent before sellers can release assets.

**Buyers** should either bring a laptop with them to mark the payment as sent, or they should click the `Payment sent` button before meeting the seller. Otherwise, the buyer will pay the seller and have to walk away without the assets they paid for.

**Sellers** should bring a laptop with their Bisq client running no matter what. Once they receive a legitimate payment, they'll need to mark the payment as received so the assets are released to the buyer. No buyer will want to walk away after paying without proof of a complete deal.

=== Arbitration

The lack of verifiable actions makes arbitrating face-to-face disputes much harder.

The same arbitration process is in place for F2F trades, but be advised that arbitrators often won't have a way to settle disputes. This means funds may be held indefinitely, or until both parties can reach an agreement.

Arbitrators may attempt different tactics to get a handle on the situation. For example, they may ask a potential scammer for ID verification, which is a request a real scammer probably wouldn't comply with.
