= How to add a new country for national bank transfer payment method
:toc:

== Introduction

We maintain a data structure for countries, regions (continents) and languages. To add a missing country we invite the requester to make a GitHub pull request if they are familiar with Java and GitHub. Otherwise please provide the country code (a two-letter ISO 3166 code), continent and language code (a two-letter ISO 639-1 code) as described below and post that to the GitHub issue. That will reduce effort for other contributors when making a pull request.


== Instructions

=== Step 1: Add an entry to the `regionByCountryCodeMap` in the `CountryUtil` class

In class `io.bisq.common.locale.CountryUtil` there is a static initializer where the country and the region (continent) is defined. Please add a comment for the full name as well. Add newly added countries at the end of the list.

First entry (key) is the ISO 3166 code of the country, e.g.:

    regionByCountryCodeMap.put("PR", "NA"); // Puerto Rico / North America

Second entry (value) is region code as defined in `regionCodeToNameMap`:

    regionCodeToNameMap.put("NA", "North America");
    regionCodeToNameMap.put("SA", "South America");
    regionCodeToNameMap.put("AF", "Africa");
    regionCodeToNameMap.put("EU", "Europe");
    regionCodeToNameMap.put("AS", "Asia");
    regionCodeToNameMap.put("OC", "Oceania");


=== Step 2: Add an entry to the `allLocales` list in `LocaleUtil` class

In class `io.bisq.common.locale.LocaleUtil` at method `getAllLocales` add the locale entry with the language if known (otherwise use English and annotate with a comment that the language is not set). If multiple languages are supported in that country use the most common language.

The first parameter is the https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes[ISO 639-1 code]. The second parameter is the ISO 3166 country code (as used above). The third parameter leave empty. Please add a comment for the full name as well. Add new added countries at the end of the list, e.g.:

    allLocales.add(new Locale("es", "PR", "")); // Puerto Rico


=== Step 3: Make a pull request to the `master` branch

Please see https://github.com/bisq-network/docs/blob/master/CONTRIBUTING.adoc[CONTRIBUTING.md] for detailed instructions.
