= How to add a new country for national bank transfer payment method
:toc:

== Introduction

We maintain a data structure for countries, regions (continents) and languages. +
To add a missing country we invite the requester to make a Github pull request if they are familiar with Java and Github. +
Otherwise please provide the country code (2 letter ISO 3166 code), continent and language code (2 letter ISO 639-1 code) as described below and post that to the Github issue. That will reduce effort for other contributors when making a PR.


== What needs to be changed?

There are 2 classes containing the relevant data:

In `io.bisq.common.locale.CountryUtil` there is a static initializer where the country and the region (continent) is defined. +
Please add a comment for the full name as well. Add new added countries at the end of the list.

First entry (key) is the ISO 3166 code of the country. Second entry (value) is region code as defined in regionCodeToNameMap [*]

E.g.: `regionByCountryCodeMap.put("PR", "NA"); // Puerto Rico / North America`


The second class to edit is: `io.bisq.common.locale.LocaleUtil`. +
At method `getAllLocales` add the language if known (otherwise use English and annotate with a comment that the language is not set. If multiple languages are supported in that country use the most common language.

First entry (key) is ISO 639-1 code (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Second entry (value) is the ISO 3166 country code (as used above). +
Please add a comment for the full name as well. Add new added countries at the end of the list.

E.g.: `allLocales.add(new Locale("es", "PR", "")); // Puerto Rico`


Please make a pull request to the Development branch.

[*] regionCodeToNameMap: +
regionCodeToNameMap.put("NA", "North America"); +
regionCodeToNameMap.put("SA", "South America"); +
regionCodeToNameMap.put("AF", "Africa"); +
regionCodeToNameMap.put("EU", "Europe"); +
regionCodeToNameMap.put("AS", "Asia"); +
regionCodeToNameMap.put("OC", "Oceania");
