= How to list a token
:toc:

IMPORTANT: PLEASE DO NOT SUBMIT ANY PULL REQUESTS FOR NEW ALTCOINS / TOKENS UNTIL FURTHER NOTICE. Bisq's repositories have recently been restructured, and the instructions below are now out-of-date. We are working on changes that will make it possible to submit token listing pull requests again soon. Subscribe to https://github.com/bisq-network/bisq-desktop/issues/1456 to be notified of progress. Thank you.

== Introduction

This document describes the process how to submit a request for adding a new altcoin or token (we use the general term _token_ in this document) to the currency list in Bisq. Adding a token does not mean any endorsement of the token. For making decisions in case of controversial requests we use the Bisq DAO voting process. The maintainers of the GH repository have the authority to merge or reject the PR based on the formal requirements but not on "political" objections (e.g. if we consider the token to be a scam, etc).

Please note that Bisq is not implementing technically any token infrastructure, e.g. wallet, full node, block explorer, etc. Rather, we only support users adding a token address as a payment account that will be used to settle a trade for bitcoin. The process of sending and receiving the token is not part of the Bisq application; traders must use their own token wallets to perform the actual transfer.

NOTE: This document replaces the earlier process description in the link:https://bisq.community/t/how-to-add-your-favorite-Altcoin/46[Bisq forum].


== Prerequisites

=== Block explorer

The token must have an active, publicly available block explorer.

=== The ticker symbol does not conflict with national currency tickers

The ticker symbol must not conflict with one of the national currency ISO 4217 ticker symbols listed at https://en.wikipedia.org/wiki/ISO_4217.

=== The ticker symbol does not conflict with other crypto-currency tickers

The ticker symbol must not conflict with one of the top 100 cryptocurrency ticker symbols listed at: https://coinmarketcap.com/currencies at the time of PR creation.

=== The token does not have extra requirements

Be sure that the requirements to add the token does not cause extra effort for Bisq maintainers, e.g. requiring additional input fields because the address alone is not sufficient for a trade.

=== Arbitrators must be able to look up transactions in the block explorer

The arbitrator must be able to look up transaction in the token's block explorer by using the receiver's address. In case that is not possible as a result of enhanced privacy features (Zcash, Monero, CryptoNote coins, etc) a suggested solution needs to be added to the PR (e.g. in Zcash we support only transparent addresses not z-addresses; in Monero we require that the user is using a Monero wallet which supports transaction keys to enable 3rd party audits of the transaction which is used in case of a dispute). As such additional cases require additional effort (popup with background info) it will be up to Bisq contributors whether to add a PR for the popup and translation strings. Of course the code or the popup can be part of the PR as well but a more detailed description is out of scope of this document.


== Instructions

=== Step 1. Add address validation logic

Add code for address validation to method `validate` in class `io.bisq.gui.util.validation.AltCoinAddressValidator`.

=== Step 2. Add address validation tests

Add unit tests with different addresses of the token to class `io.bisq.gui.util.AltCoinAddressValidatorTest` and run the tests to see if they succeed.

=== Step 3. Add token to currency list

Add entry for the token to method `createAllSortedCryptoCurrenciesList` in class `io.bisq.common.locale.CurrencyUtil`.
First parameter is ticker, second parameter token name and the optional third parameter is the boolean `isAsset` parameter. Set that to true in case the token is not using a dedicated blockchain but is issued on other blockchains (e.g. colored coins, ETH tokens,...). The list is *ordered alphabetic by token name*. Add your entry at the correct position!

==== Examples

----
// token with dedicated blockchain
result.add(new CryptoCurrency("XMR", "Monero"));

// token issued on another blockchain
result.add(new CryptoCurrency("MT", "Mycelium Token", true));
----

=== Step 4. Add token to trade statistics manager

Open `o.bisq.core.trade.statistics.TradeStatisticsManager` and add at method `printAllCurrencyStats` the entry at the end of the list:

----
newlyAdded.add([TOKEN CODE]);
----

=== Step 5. Compile and test

----
mvn test
----

=== Step 6. Submit pull request

----
- Ticker symbol (e.g. LTC): ...
- Official token name (e.g. Litecoin): ...
- Official block explorer URL: ...
- Is it an altcoin (dedicated blockchain) or a token (anything else) (e.g. altcoin): ...
- Official token project URL: ...
----

Submit a pull request with your changes to the bisq-network/exchange repository's `master` branch. Make sure you do this from a dedicated topic branch in your fork named, for example, `list-foo-token`. Do not submit your pull request directly from your `master` branch, as this can make things unnecessarily complex if and when there are merge conflicts.

Copy and paste the form template below into the description of the pull request and fill it out.

== Caveats

=== Controversial tokens may be put to a vote

 - Any BSQ token holder can request that a decision for adding the token should be decided in the Bisq DAO voting process (the Bisq DAO will be executed in a manual manner as long the full DAO version is not implemented according to the DAO phase 0 doc TODO: add link, not available atm).
 - If such a request for voting is filed the PR will be delayed until the next voting period. Filing a request for voting is described in the DOA voting document (TODO: add link, not available atm).
 - If the voting has > 50% of votes and reaches the required quorum (at least 5% of total BSQ stake need to vote on it) the result will be used to accept or reject the token. Not reaching the quorum results in a rejection.
 - For requesting again a token which got rejected by voting it requires a clear statement about the changed circumstances. Objecting the political positions is not sufficient (e.g. Coin XXX is not a scamcoin because of ....).
 - Any BSQ token holder can also request a voting to remove an already supported token.

=== Inactive tokens will be de-listed

 - At each new release we will check if already added tokens have been traded in the past 4 months. If this requirement is not met the token will be removed. The Bisq trade statistics are taken as reference. Removal of a not-traded token will not be announced beside in the release notes of the new release.
 - Adding the token again requires a statement about the changed circumstances (e.g. link to discussions where demand for the token is documented, etc).

=== Getting a new token into production may take a while

Adding a new token will be part of the normal release cycle. Whenever we ship the next Bisq release, your token will be included.

=== Making a PR with not compiling code or with unit tests failing will lead to a blocking period for 2 weeks

To not waste developer time for reviewing a PR which does not fulfill the very basic requirements we will add a policy to block updated PRs for that token for 2 weeks. The PR will get closed and has to be re-opened after that period with the fixes.
