= Requirements for making a request for adding an Altcoin or token
:toc:

== Introduction

This document describes the process how to submit a request for adding a new Altcoin or token to the currency list in Bisq. +
Adding a coin/token does not mean any endorsement from the Bisq community. For making decisions in case of controversial requests we use the Bisq DAO voting process. +
Please don't send promotional/background information about the coin/token but only fulfill the formal requirements below.

Please note that Bisq is not implementing technically any coin/token infrastructure (wallet, full nodes, block explorer,...) but only supports that the users can add the altoin address to a payment account and then during the trade process the users exchange the Altcoin address. The process of sending and receiving the Altcoin is not part of our system (users use their own Altcoin wallets).

Already added coins/tokens which have been traded at least once or which have provided a PR for the address validation will be kept. All other coins/tokens will be removed when we start introducing that requirements. +
This document replaces the process described in the Bisq forum [1].

== Process

* Any request has to be done via a pull request (PR) in Github (GH) to the Development branch.
* The request needs to fulfill the formal requirements as described below.
* Anyone can file such a PR.
* Anyone can comment or object against the PR.
* The maintainers of the GH repository have the authority to merge or reject the PR based on the formal requirements but not on "political" objections (e.g. consider the coin as scamcoin,...).
* Any BSQ token holder can request that a decision for adding the coin/token will be decided in the voting process of the Bisq DAO [*].
* If such a request for voting is filed the PR will be delayed until the next voting period. Filing a request for voting is described in the DOA voting document (TODO: not available atm).
* Any BSQ token holder can request a voting to remove an already supported coin/token.
* If the voting has > 50% of votes and reaches the required quorum (at least 5% of total BSQ stake need to voted on it) the result will be used to accept or reject the coin/token. Not reaching the quorum means a rejection.
* Adding a new coin/token will be part of the normal release cycle.
* At each new release we will check if already added coins/tokens have reached the min. usage requirements (see below). If those requirements are not met the coin/token will be removed. Adding the token again requires a statement about the changed circumstances (e.g. link to discussions where users demand for the coin/token is documented,...).
* For requesting again a coin/token which got rejected by voting it requires a clear statement about the changed circumstances. Objecting the political positions is not sufficient (e.g. Coin XXX is not a scamcoin because of ....).
* PR which fail to fulfill the formal requirements (e.g. failing address validation unit tests) will result that the coin/token will be blocked for 3 months.

[*] The Bisq DAO will be executed in a manual manner as long the full DAO version is not implemented.
See: link to DAO phase 0 doc. (TODO)


== Formal requirements

* The PR need to use the below form and has answered all questions.
* There need to be an active block explorer available.
* The ticker symbol must not conflict with one of the national currency ISO 4217 ticker symbols listed at: https://en.wikipedia.org/wiki/ISO_4217
* The ticker symbol must not conflict with one of the top 100 crypto-currency ticker symbols at time when the PR gets created listed at: https://coinmarketcap.com/currencies/
* The PR need to contain code for address validation [2] of the coin/token and unit tests[3] for that validation.
* The PR need to contain code which adds the coin to the list of coins/tokens [4]. Use the optional "true" parameter if the coin is a token (no dedicated blockchain). Add the coin according to alphabetic order based on the name (not ticker).
* The requirements to add the coin does not cause extra effort for Bisq like adding additional input fields (e.g. if the address alone is not sufficient for the trade).
* The arbitrator need to be able to see the transaction in the block explorer by using the receiver address. In case that is not possible as a result of enhanced privacy features (Zcash, Monero, CryptoNote coins,...) a suggested solution need to be added to the PR (e.g. in Zcash we support only transparent addresses not z-addresses; in Monero we require that the user is using a Monero wallet which supports transaction keys to enable 3rd party audits of the transaction which is used in case of a dispute). As such additional cased require additional effort (popup with background info) it will be up to Bisq contributors to add a PR for the popup and translation strings. Of course the code or the popup can be part of the PR as well but a more detailed description is out of scope of that document.


== Form to be filled out and be pasted into the PR

* Ticker symbol (e.g. LTC): ...
* Official coin name (e.g. Litecoin): ...
* Official block explorer URL: ...
* Is it an Altcoin (dedicated blockchain) or a token (anything else) (e.g. Altcoin): ...
* Official coin/token project URL: ...


== Min. usage requirements

* Any coin/token need to have at least been traded once in the past 4 months. The Bisq trade statistics are taken as reference. Removal of a not-traded coin/token will not be announced beside in the release notes of the new release.


== References

[1] https://forum.bisq.io/t/how-to-add-your-favorite-Altcoin/46 +
[2] https://github.com/bisq-network/exchange/blob/Development/gui/src/main/java/io/bisq/gui/util/validation/AltCoinAddressValidator.java +
[3] https://github.com/bisq-network/exchange/blob/Development/gui/src/test/java/io/bisq/gui/util/validation/AltCoinAddressValidatorTest.java +
[4] https://github.com/bisq-network/exchange/blob/master/common/src/main/java/io/bisq/common/locale/CurrencyUtil.java#L86 +
