= How to run a seed node
:stylesdir: ../../css
:docinfodir: ../../

== Introduction

Bisq seed nodes serve as static gateways for Bisq clients to get connected to Bisq's dynamic P2P network. In this section, you will find information about

- what a seed node is and how it works,
- the duties of a seed node operator,
- the benefits of being a seed node operator,
- how to get a seed node up and running and
- where to get in touch.

== What is a Bisq seed node

Bisq uses a highly anonymous and dynamic P2P network for communications between Bisq clients. In order to get access to the network, the Bisq network features always-up Bisq clients with a static addresses: seed nodes. They have 2 main tasks:

. Deliver the peer addresses of other dynamic network peers

. Deliver the initial P2P network data like open offers, mailbox messages and arbitrators

Being the gateways to the Bisq P2P network, seed nodes are among the first nodes a Bisq client connects to on startup. Thus, seed nodes face a heavy load and are therefore operated on servers offering a high level of reliability and better connectivity than a normal Bisq client.

A bad seed node can have a substantial impact on the Bisq network. A Bisq user may encounter anything from a longer startup time of his Bisq client (which is unconvenient but not critical) to missing messages sent to him by a trading partner or arbitrator while his Bisq client has been offline (which can lead to disputes, failed trades, blocking of the Bisq client and bad reputation of the Bisq client and therefore the user). 

All in all, seed nodes are mandatory and critical for the Bisq network to function properly. If all goes wrong, mechanisms are in place to ban a bad seed node and therefore, limit its impact on the network.

== Seed node operators

Being a seed node operator brings along duties and benefits making it worthwhile.

=== Duties of the seed node operator

The operator of a seed node needs to:

- keep the server up and running, including patching and hardening the operating system
- keep the seed node software up to date
- keep an eye on the Bisq's communication channels for updates, issues, countermeasures,... (see <<Getting in Touch>>)
- keep an eye on the logs of the seed node and the operating system, and act if something shows up
- if necessary, report (see <<Getting in Touch>>)
- set up a bond of 2000 BSQ to get the privilege to run a seed node. In case of severe failure of service, the bond is be confiscated (burned).

=== Payment

A seed node operator has the right to:

- file a compensation request over 200 BSQ for setting up a seed node
- file a compensation monthly request. We define 50 BSQ per month as an appropriate compensation per seed node per month.


## Get a seed node up and running

=== System requirements for hosting machine

. Min. 2 GB of RAM
. 10 GB disk space (SSD)
. 2 TB network traffic
. UPS (uninterruptible power supply)
. Uptime of > 99.9%

=== Setup instructions
You can run your seed node in two ways:

- Option A: use the systemd service file provided
- Option B: create and use a shell script to run your seednode

==== Step 1. Install latest JDK

You need to have the latest JDK installed according to the link:https://github.com/bisq-network/exchange/blob/master/doc/build.md[build.md] file.

==== Step 2. Install Bisq on your server

We recommend cloning the Bisq Git repository and compiling the code on your server. This way, you have precise control over what version you want to deploy. Starting with "master" is a good place to start.

Furthermore, we recommend creating a user `bisq` in group `bisq` for service hardening reasons and using the `bisq`-users home directory to:

- install git
- `git clone git@github.com:bisq-network/bisq.git`
- `cd bisq`
- `git checkout <insert your release tag here>` (optional)
- `./gradlew build`

==== Step 3. Start your seed node

==== Option A: Use systemd to run your service
===== 1. Register your service

Copy the file `bisq-seednode.service` to your systemd service directory. 

`cp seednode/bisq-seednode.service /usr/lib/systemd/system/`

and adapt it to your needs.

===== 2. Enable and start the seed node

Enable and start the seed node by

`systemctl enable bisq-seednode.service` +
`systemctl start bisq-seednode.service`

===== 3. Observe the logs

Keep an eye on the logs and see if anything works as expected:

`journalctl --unit bisq-seednode --follow`

==== Option B: Use a shell script
===== 1. Create two shell scripts:

start_btc_ONION_ADDRESS.sh: +
`nohup sh loop_btc_ONION_ADDRESS.sh &`

loop_btc_ONION_ADDRESS.sh: +
`java -Xms1800m -Xmx1800m -jar SeedNode.jar --maxConnections=30 --baseCurrencyNetwork=BTC_MAINNET --nodePort=8000 --appName=seed_BTC_MAINNET_ONION_ADDRESS >/dev/null 2>error_seed_BTC_MAINNET_ONION_ADDRESS.log`

and make them executable.

===== 2. Start your seed node

run the `start_btc_ONION_ADDRESS.sh` script

===== 3. Get onion address from log

After about 40 seconds you should see in the logs something similar to:
`INFO  c.m.t.t.OnionProxyManagerEventHandler: Hidden service <ONION_ADDRESS:port> published.`

This is the onion address you need to use in the next step to replace the ONION_ADDRESS place holder.

===== 4. Replace placeholder with real onion address

Stop the node and replace the occurrence of ONION_ADDRESS in the above listed scripts and their file names.

Go to `~/.local/share` and replace ONION_ADDRESS in the directory name with the real onion address.

===== 5. Start seed node again

Once all the renaming is done you can finally start the seed node and it will be available to the network. Check if all is running as expected.

==== Step 4. Backup private key for onion address

Go to `~/.local/share/seed_BTC_MAINNET_ONION_ADDRESS/btc_mainnet/tor/hiddenservice/` and backup the private key and the hostname file in a safe location. If your server would crash you can re-install the same seed node with the private key. All other data like the `db` or the `keys` directory are not relevant for the seed node.

==== Step 5. Take over an existing seed node

In case you are about to take over a seed node from someone, you need the contents of their `~/.local/share/seed_BTC_MAINNET/` (Option A)/`~/.local/share/seed_BTC_MAINNET_ONION_ADDRESS/` (Option B) directory, replace your directory with their contents and restart the server.


=== System health reports

- install nginx
- create a certificate

  cd /etc/nginx
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.crt

with

  ON = bisq.network
  OU = seednodes
  CN = <your seed nodes onion address here>

- configure a reverse proxy with clientssl enabled

----
stream {
	log_format basic '$remote_addr [$time_local] '
	                 '$protocol Status $status Sent $bytes_sent Received $bytes_received '
	                 'Time $session_time';

	error_log syslog:server=unix:/dev/log;
	access_log syslog:server=unix:/dev/log;

	server {
		listen 2003;
		proxy_pass monitor.bisq.network:2003;
		proxy_ssl on;

		proxy_ssl_certificate /etc/nginx/cert.crt;
		proxy_ssl_certificate_key /etc/nginx/cert.key;

		proxy_ssl_session_reuse on;
	}
}
----

- install collectd
- use link:collectd.conf[this] collectd config to start from

fill in the onion address of your seed node

  Hostname "<ONION_ADDRESS>"

and adjust the interface, df, disk plugins so they match your setup

- configure your seed node process to expose jmx information by adding

   -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=6969 -Dcom.sun.management.jmxremote.rmi.port=6969 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

to your service

- start nginx and collectd
- report your client certificate in slack


== Getting in Touch

Bisq uses Slack to communicate via chat. As a seed node operator, you are required to

- subscribe to the Bisq Slack channel `bisq-seednode` and `bisq-monitor`
- the `bisq-seednode` channel is the place where updates, issues, countermeasures, heads-ups, ... are discussed. If you encounter a problem with your seed node and cannot solve it by yourself, this is the place to report to (with a specific question, logs, ...). A developer will get back to you.
- the `bisq-monitor` channel is the place where issues with seed nodes are reported, either manually or by our monitoring service. If your seed node is mentioned for having an issue, you are required to react.
- please be responsive when addressed
