= How to run a seed node
:stylesdir: ../../css
:docinfodir: ../../

== Introduction

Bisq seed nodes serve as static gateways for Bisq clients to get connected to Bisq's dynamic P2P network. In this section, you will find information about

- what a seed node is and how it works,
- the duties of a seed node operator,
- the benefits of being a seed node operator,
- how to get a seed node up and running and
- where to get in touch.

== What is a Bisq seed node

Bisq uses a highly anonymous and dynamic P2P network for communications between Bisq clients. In order to get access to the network, the Bisq network features always-up Bisq clients with a static addresses: seed nodes. They have 2 main tasks:

. Deliver the peer addresses of other dynamic network peers

. Deliver the initial P2P network data like open offers, mailbox messages and arbitrators

Being the gateways to the Bisq P2P network, seed nodes are among the first nodes a Bisq client connects to on each startup. Therefore, seed nodes have distinct properties:

- Seed nodes face a heavy load and are therefore operated on servers offering a high level of reliability and better connectivity than a normal Bisq client.
- A bad seed node can have a substantial impact on the Bisq network. A Bisq user may encounter anything from a longer startup time of her Bisq client (which is unconvenient but not critical) to missing messages sent to her by a trading partner or arbitrator while her Bisq client has been offline (which can lead to disputes, failed trades, blocking of the Bisq client and bad reputation of the Bisq client and therefore the user). 

All in all, seed nodes are mandatory and critical for the Bisq network to function properly. Without the seed nodes, a fresh client would never find its way into the network and would therefore be denied the services of Bisq. Malicious seed nodes can trick fresh clients, cause monetary fraud and if all is said and done, again deny them the services of Bisq.

== Seed node operators

Being a seed node operator brings along duties and benefits making it worthwhile.

=== Duties of the seed node operator

The operator of a seed node needs to:

- keep the server up and running, including patching and hardening the operating system
- keep the seed node software up to date
- keep an eye on the Bisq's communication channels for updates, issues, countermeasures,... (see <<Getting in Touch>>)
- keep an eye on the logs of the seed node and the operating system, and act if something shows up
- if necessary, report and escalate (see <<Getting in Touch>>)
- set up a bond of 2000 BSQ to get the privilege to run a seed node. In case of severe failure of service, the bond gets confiscated (burned).

=== Payment

A seed node operator has the right to:

- file a compensation request over 200 BSQ for setting up a seed node
- file a monthly compensation request. We define 50 BSQ per month as an appropriate compensation per seed node per month.

== Getting in Touch

Bisq uses Slack to communicate via chat. As a seed node operator, you are required to

- subscribe to the Bisq Slack channel `bisq-seednode` and `bisq-monitor`
- the `bisq-seednode` channel is the place where updates, issues, countermeasures, heads-ups, ... are discussed. If you encounter a problem with your seed node and cannot solve it by yourself, this is the place to report to (with a specific question, logs, ...). A developer will get back to you.
- the `bisq-monitor` channel is the place where issues with seed nodes are reported, either manually or by our monitoring service. If your seed node is mentioned for having an issue, you are required to react.
- please be responsive when addressed

== System requirements for hosting machine

. Min. 2 GB of RAM
. 10 GB disk space (SSD)
. 2 TB network traffic
. UPS (uninterruptible power supply)
. Uptime of > 99.9%

## Get a seed node up and running

There are three pieces to the puzzle of successfully running a seed node:

- a Bitcoin full node
- the Bisq seednode itself and
- system health reports.

You can run your seed node in many ways. The guide here applies to a (debian-based) unix system with systemd available. Furthermore, we assume that only one seed node is operated per host. In case your host differs from our reference system, we are sure you can handle yourself.

=== Bitcoin Node

Follow https://bitcoin.org/en/full-node#linux-instructions[this guide] to install the binaries. Create a systemd service file `bitcoind.service` in the systemd service path or your operating system (something like `/usr/lib/systemd/system/`) and adapt it to your needs. We recommend to create a user `bitcoind` for service hardening reasons (`useradd -r -m bitcoind`). In the end, it should look like 

----
[Unit]
Description=Bitcoind
After=network.target

[Service]
ExecStart=bitcoind -daemon

Restart=on-failure

User=bitcoind
Group=bitcoind

PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
PrivateDevices=true
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
----

Create a file `/home/bitcoind/.bitcoin/bitcoin.conf` that contains something like

----
rpcport=8332
server=1
txindex=1
dbcache=1000
maxconnections=800
timeout=30000
listen=0
rpcallowip=localhost
rpcuser=YOUR_USER_NAME
rpcpassword=YOUR_PW
blocknotify=sh ~/.bitcoin/blocknotify.sh %s
----

and another file `/home/bitcoind/.bitcoin/blocknotify.sh` that contains

  #!/bin/sh
  echo $1 | nc -w 1 127.0.0.1 5120

and make it executable (`chmod +x /home/bitcoind/.bitcoin/blocknotify.sh`).

Finally, enable and start the service

  systemctl enable bitcoind.service
  systemctl start bitcoind.service

and observe the logs

  journalctl --unit bitcoind --follow

an check if anything works as expected.

=== Bisq Seed Node

You need to have the latest JDK installed according to the link:https://github.com/bisq-network/exchange/blob/master/doc/build.md[build.md] file.

For getting the Bisq binaries, we recommend cloning the Bisq Git repository and compiling the code on your server. This way, you have precise control over what version you want to deploy. Furthermore, updating is very simple, just pull the changes, recompile and restart your service.

Furthermore, we recommend creating a user `bisq` in group `bisq` for service hardening reasons and using the `bisq`-users home directory to:

  useradd -r -m bisq
  cd /home/bisq
  git clone git@github.com:bisq-network/bisq.git
  cd bisq
  ./gradlew build

Create a systemd service file `bisq-seednode.service` (or copy the one shipped with bisq `$bisqdir/seednode/bisq-seednode.service`) in the systemd service path or your operating system (something like `/usr/lib/systemd/system/`) and adapt it to your needs.

In the end, your file should look something like

----
[Unit]
Description=Bisq Seed Node
After=network.target

[Service]
Environment="JAVA_OPTS=-Xms800M -Xmx800M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=6969 -Dcom.sun.management.jmxremote.rmi.port=6969 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
ExecStart=/home/bisq/bisq/bisq-seednode --appName=bisq-seednode --nodePort=8000 --userDataDir=/home/bisq/ --maxConnections=50 --daoActivated=true --fullDaoNode=true --rpcUser=YOUR_USER_NAME --rpcPassword=YOUR_PW --rpcPort=8332 --rpcBlockNotificationPort=5120

Restart=on-failure

User=bisq
Group=bisq

PrivateTmp=true
ProtectSystem=full
NoNewPrivileges=true
PrivateDevices=true
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
----

Note that the jmxremote JVM arguments are later used for monitoring the service, the rpc arguments are there to get the seed node hooked to the bitcoin service. Make sure, the YOUR_USER_NAME and YOUR_PW placeholders match the configuration of <<Bitcoin Node>>.

Enable and start the seed node by


`systemctl daemon-reload` +
`systemctl enable bisq-seednode.service` +
`systemctl start bisq-seednode.service`

Keep an eye on the logs and see if anything works as expected:

`journalctl --unit bisq-seednode --follow`

In case you are about to take over a seed node from someone else, you need to manually import their onion address and private key.

In `/home/bisq/.local/share/bisq_seednode/btc_mainnet/tor/hiddenservice/`, replace the files 

  hostname
  private_key

with the ones you received from the former seed node operator. Restart your service

`systemctl restart bisq-seednode.service` and again, observe the logs and make sure everything works as expected.

Finally, we ask you to prepare for the worst. Go to `/home/bisq/.local/share/bisq-seednode/btc_mainnet/tor/hiddenservice/` and backup the files

  hostname
  private_key

to a secure location. In case your server loses the original files during a crash, you can recover easily by following the steps for taking over a seed node. All other data like the `db` or the `keys` directory are not relevant for the seed node.


=== System health reports

Since seed nodes are such a crucial part of the Bisq network, we require periodic health reports to our https://monitor.bisq.network[monitor]. Since the monitor only accepts plain TCP connections for incoming data, we have to accept a bit of overhead to keep the monitor from being flooded with unauthorized input.

In order to successfully report to the monitor, we need to create a TCP reverse proxy local to your host that can authenticate to the monitor. For this guide, we go with nginx, if you prefer another reverse proxy, we are sure you can handle yourself.

First of all, if you have not already, install nginx on your system.

Then proceed to creating the SSL certificate that is later used to authenticate against the monitor:

  cd /etc/nginx
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.crt

Use `ON = bisq.network`, `OU = seednodes` and `CN = <your seed nodes onion address here (without the ".onion" part)>` for certificate creation. The onion address can be found in the `hostname`-file mentioned before.

Configure the reverse proxy with clientssl enabled. You can simply append the snipped below to your `/etc/nginx/nginx.conf` file:

----
stream {
	log_format basic '$remote_addr [$time_local] '
	                 '$protocol Status $status Sent $bytes_sent Received $bytes_received '
	                 'Time $session_time';

	error_log syslog:server=unix:/dev/log;
	access_log syslog:server=unix:/dev/log basic;

	server {
		listen 2003;
		allow 127.0.0.1;
		deny all;
		proxy_pass monitor.bisq.network:2003;
		proxy_ssl on;

		proxy_ssl_certificate /etc/nginx/cert.crt;
		proxy_ssl_certificate_key /etc/nginx/cert.key;

		proxy_ssl_session_reuse on;
	}
}
----

Start your nginx and observe the logs to see if anything works as expected:

  systemctl restart nginx
  journalctl --unit nginx --follow

Once you are satisfied, proceed on installing https://collectd.org/[collectd] and use link:collectd.conf[this] collectd config to start from. Fill in the onion address of your seed node

  Hostname "<ONION_ADDRESS again without the ".onion">"

and adjust the interface, df, disk plugins so that they match your setup (and thus, report meaningful metrics).

Start your collectd service and check the logs for any issues:

  systemctl restart collectd
  journalctl --unit collectd --follow

Once you are satisfied, go ahead and report your client certificate (`/etc/nginx/cert.crt`) to the `bisq-seednode` channel (see <<Getting in Touch>>). The monitoring team will then whitelist your host and you can enjoy your metrics at https://monitor.bisq.network.
