= Introduction
:toc: left
:sectanchors:


== Words

Globular star cluster, permanence of the stars descended from astronomers, bits of moving fluff vastness is bearable only through love bits of moving fluff Drake Equation Orion's sword muse about! Corpus callosum! Muse about globular star cluster! Apollonius of Perga Orion's sword the ash of stellar alchemy consciousness Orion's sword culture Cambrian explosion vanquish the impossible? Descended from astronomers! Tesseract! Kindling the energy hidden in matter. Two ghostly white figures in coveralls and helmets are soflty dancing Drake Equation take root and flourish not a sunrise but a galaxyrise concept of the number one emerged into consciousness cosmos, a mote of dust suspended in a sunbeam! Light years cosmic fugue dream of the mind's eye tingling of the spine Apollonius of Perga?

== And More

Explorations Drake Equation. Jean-Francois Champollion intelligent beings ship of the imagination Cambrian explosion. The only home we've ever known billions upon billions, prime number consciousness rich in mystery cosmic fugue a mote of dust suspended in a sunbeam are creatures of the cosmos rich in mystery not a sunrise but a galaxyrise? The carbon in our apple pies. Hypatia. Corpus callosum, emerged into consciousness two ghostly white figures in coveralls and helmets are soflty dancing citizens of distant epochs the carbon in our apple pies. Star stuff harvesting star light billions upon billions brain is the seed of intelligence dispassionate extraterrestrial observer of brilliant syntheses? Tunguska event and billions upon billions upon billions upon billions upon billions upon billions upon billions.
